// react-products-app/src/components/ProductDetail.tsx
import {
	Dialog,
	DialogPanel,
	DialogTitle,
	Transition,
	TransitionChild,
} from '@headlessui/react'
import { Fragment, useEffect, useState } from 'react'
import { productsApi } from '../api/products'
import type { Product } from '../types/product'

interface Props {
	open: boolean
	productId: number | null
	onClose: () => void
}

export default function ProductDetail({ open, productId, onClose }: Props) {
	const [product, setProduct] = useState<Product | null>(null)
	const [loading, setLoading] = useState(false)
	const [error, setError] = useState<string | null>(null)

	useEffect(() => {
		if (!open || !productId) {
			setProduct(null)
			return
		}

		let cancelled = false
		setLoading(true)
		setError(null)
		productsApi
			.get(productId)
			.then((p) => {
				if (!cancelled) setProduct(p)
			})
			.catch((err) => {
				if (!cancelled)
					setError(err instanceof Error ? err.message : 'Load failed')
			})
			.finally(() => {
				if (!cancelled) setLoading(false)
			})

		return () => {
			cancelled = true
		}
	}, [open, productId])

	return (
		<Transition show={open} as={Fragment}>
			<Dialog onClose={onClose} className="relative z-50">
				<TransitionChild
					as={Fragment}
					enter="ease-out duration-200"
					enterFrom="opacity-0"
					enterTo="opacity-100"
					leave="ease-in duration-150"
					leaveFrom="opacity-100"
					leaveTo="opacity-0"
				>
					<div className="fixed inset-0 bg-slate-900/40" aria-hidden="true" />
				</TransitionChild>
				<div className="fixed inset-0 flex items-center justify-center p-4">
					<TransitionChild
						as={Fragment}
						enter="ease-out duration-200"
						enterFrom="opacity-0 scale-95"
						enterTo="opacity-100 scale-100"
						leave="ease-in duration-150"
						leaveFrom="opacity-100 scale-100"
						leaveTo="opacity-0 scale-95"
					>
						<DialogPanel className="w-full max-w-xl rounded-xl bg-white p-6 shadow-xl">
							<DialogTitle className="text-lg font-semibold">
								{product?.title ?? 'Product details'}
							</DialogTitle>
							<div className="mt-4 text-sm text-slate-700">
								{loading && <p className="text-slate-500">Loading…</p>}
								{error && <p className="text-rose-600">{error}</p>}
								{product && (
									<div className="space-y-3">
										{product.thumbnail && (
											<img
												src={product.thumbnail}
												alt=""
												className="h-40 w-full rounded-md object-cover"
											/>
										)}
										<p>{product.description}</p>
										<dl className="grid grid-cols-2 gap-3">
											<Info label="Category" value={product.category} />
											<Info label="Brand" value={product.brand ?? '—'} />
											<Info
												label="Price"
												value={`$${product.price.toFixed(2)}`}
											/>
											<Info
												label="Discount"
												value={`${product.discountPercentage}%`}
											/>
											<Info label="Stock" value={String(product.stock)} />
											<Info label="Rating" value={product.rating.toFixed(2)} />
										</dl>
									</div>
								)}
							</div>
							<div className="mt-6 flex justify-end">
								<button
									type="button"
									onClick={onClose}
									className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
								>
									Close
								</button>
							</div>
						</DialogPanel>
					</TransitionChild>
				</div>
			</Dialog>
		</Transition>
	)
}

function Info({ label, value }: { label: string; value: string }) {
	return (
		<div>
			<dt className="text-xs uppercase tracking-wide text-slate-500">
				{label}
			</dt>
			<dd className="text-sm text-slate-900">{value}</dd>
		</div>
	)
}

// vue-pinia/src/components/ProductDetail.vue
<script setup lang="ts">
import {
  Dialog,
  DialogPanel,
  DialogTitle,
  TransitionChild,
  TransitionRoot,
} from '@headlessui/vue';
import { ref, watch } from 'vue';
import { productsApi } from '../api/products';
import type { Product } from '../types/product';

const props = defineProps<{
  open: boolean;
  productId: number | null;
}>();
defineEmits<(e: 'close') => void>();

const product = ref<Product | null>(null);
const loading = ref(false);
const error = ref<string | null>(null);

watch(
  () => [props.open, props.productId],
  async () => {
    if (!props.open || !props.productId) {
      product.value = null;
      return;
    }

    loading.value = true;
    error.value = null;
    const id = props.productId;
    try {
      const p = await productsApi.get(id);
      if (props.productId === id) product.value = p;
    } catch (err) {
      error.value = err instanceof Error ? err.message : 'Load failed';
    } finally {
      loading.value = false;
    }
  },
  { immediate: true },
);
</script>

<template>
  <TransitionRoot :show="open" as="template">
    <Dialog @close="$emit('close')" class="relative z-50">
      <TransitionChild
        as="template"
        enter="ease-out duration-200"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="ease-in duration-150"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div class="fixed inset-0 bg-slate-900/40" aria-hidden="true" />
      </TransitionChild>
      <div class="fixed inset-0 flex items-center justify-center p-4">
        <TransitionChild
          as="template"
          enter="ease-out duration-200"
          enter-from="opacity-0 scale-95"
          enter-to="opacity-100 scale-100"
          leave="ease-in duration-150"
          leave-from="opacity-100 scale-100"
          leave-to="opacity-0 scale-95"
        >
          <DialogPanel class="w-full max-w-xl rounded-xl bg-white p-6 shadow-xl">
            <DialogTitle class="text-lg font-semibold">
              {{ product?.title ?? 'Product details' }}
            </DialogTitle>
            <div class="mt-4 text-sm text-slate-700">
              <p v-if="loading" class="text-slate-500">Loading…</p>
              <p v-else-if="error" class="text-rose-600">{{ error }}</p>
              <div v-else-if="product" class="space-y-3">
                <img
                  v-if="product.thumbnail"
                  :src="product.thumbnail"
                  alt=""
                  class="h-40 w-full rounded-md object-cover"
                />
                <p>{{ product.description }}</p>
                <dl class="grid grid-cols-2 gap-3">
                  <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-500">Category</dt>
                    <dd class="text-sm text-slate-900">{{ product.category }}</dd>
                  </div>
                  <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-500">Brand</dt>
                    <dd class="text-sm text-slate-900">{{ product.brand ?? '—' }}</dd>
                  </div>
                  <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-500">Price</dt>
                    <dd class="text-sm text-slate-900">${{ product.price.toFixed(2) }}</dd>
                  </div>
                  <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-500">Discount</dt>
                    <dd class="text-sm text-slate-900">{{ product.discountPercentage }}%</dd>
                  </div>
                  <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-500">Stock</dt>
                    <dd class="text-sm text-slate-900">{{ product.stock }}</dd>
                  </div>
                  <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-500">Rating</dt>
                    <dd class="text-sm text-slate-900">{{ product.rating.toFixed(2) }}</dd>
                  </div>
                </dl>
              </div>
            </div>
            <div class="mt-6 flex justify-end">
              <button
                type="button"
                @click="$emit('close')"
                class="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
              >Close</button>
            </div>
          </DialogPanel>
        </TransitionChild>
      </div>
    </Dialog>
  </TransitionRoot>
</template>
