// vue-pinia/src/components/ProductForm.vue
<script setup lang="ts">
import {
  Dialog,
  DialogPanel,
  DialogTitle,
  TransitionChild,
  TransitionRoot,
} from '@headlessui/vue';
import { reactive, ref, watch } from 'vue';
import { useProductsStore } from '../stores/products';
import type { Product, ProductDraft } from '../types/product';

const props = defineProps<{
  open: boolean;
  mode: 'create' | 'edit';
  product?: Product;
}>();
const emit = defineEmits<(e: 'close') => void>();

const store = useProductsStore();

const inputCls =
  'mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm shadow-sm focus:border-emerald-500 focus:outline-none focus:ring-1 focus:ring-emerald-500';

const empty: ProductDraft = {
  title: '',
  description: '',
  category: 'smartphones',
  price: 0,
  discountPercentage: 0,
  stock: 0,
  brand: '',
};

const draft = reactive<ProductDraft>({ ...empty });
const submitting = ref(false);
const error = ref<string | null>(null);

watch(
  () => [props.open, props.mode, props.product?.id],
  () => {
    if (!props.open) return;
    if (props.mode === 'edit' && props.product) {
      Object.assign(draft, {
        title: props.product.title,
        description: props.product.description,
        category: props.product.category,
        price: props.product.price,
        discountPercentage: props.product.discountPercentage,
        stock: props.product.stock,
        brand: props.product.brand ?? '',
      });
    } else {
      Object.assign(draft, empty);
    }
    error.value = null;
  },
  { immediate: true },
);

async function onSubmit() {
  submitting.value = true;
  error.value = null;
  try {
    if (props.mode === 'create') {
      await store.create({ ...draft });
    } else if (props.product) {
      await store.update(props.product.id, { ...draft });
    }
    emit('close');
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Save failed';
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <TransitionRoot :show="open" as="template">
    <Dialog @close="$emit('close')" class="relative z-50">
      <TransitionChild
        as="template"
        enter="ease-out duration-200"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="ease-in duration-150"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div class="fixed inset-0 bg-slate-900/40" aria-hidden="true" />
      </TransitionChild>
      <div class="fixed inset-0 flex items-center justify-center p-4">
        <TransitionChild
          as="template"
          enter="ease-out duration-200"
          enter-from="opacity-0 scale-95"
          enter-to="opacity-100 scale-100"
          leave="ease-in duration-150"
          leave-from="opacity-100 scale-100"
          leave-to="opacity-0 scale-95"
        >
          <DialogPanel class="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl">
            <DialogTitle class="text-lg font-semibold">
              {{ mode === 'create' ? 'New product' : `Edit: ${product?.title ?? ''}` }}
            </DialogTitle>
            <form @submit.prevent="onSubmit" class="mt-4 space-y-4">
              <label class="block">
                <span class="text-sm font-medium text-slate-700">Title</span>
                <input v-model="draft.title" required :class="inputCls" />
              </label>
              <label class="block">
                <span class="text-sm font-medium text-slate-700">Description</span>
                <textarea v-model="draft.description" rows="3" :class="inputCls" />
              </label>
              <div class="grid grid-cols-2 gap-3">
                <label class="block">
                  <span class="text-sm font-medium text-slate-700">Category</span>
                  <input v-model="draft.category" :class="inputCls" />
                </label>
                <label class="block">
                  <span class="text-sm font-medium text-slate-700">Brand</span>
                  <input v-model="draft.brand" :class="inputCls" />
                </label>
              </div>
              <div class="grid grid-cols-3 gap-3">
                <label class="block">
                  <span class="text-sm font-medium text-slate-700">Price</span>
                  <input
                    v-model.number="draft.price"
                    type="number"
                    step="0.01"
                    min="0"
                    :class="inputCls"
                  />
                </label>
                <label class="block">
                  <span class="text-sm font-medium text-slate-700">Discount %</span>
                  <input
                    v-model.number="draft.discountPercentage"
                    type="number"
                    step="0.01"
                    min="0"
                    :class="inputCls"
                  />
                </label>
                <label class="block">
                  <span class="text-sm font-medium text-slate-700">Stock</span>
                  <input
                    v-model.number="draft.stock"
                    type="number"
                    min="0"
                    :class="inputCls"
                  />
                </label>
              </div>
              <p v-if="error" class="text-sm text-rose-600">{{ error }}</p>
              <div class="flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  @click="$emit('close')"
                  class="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
                >Cancel</button>
                <button
                  type="submit"
                  :disabled="submitting"
                  class="rounded-md bg-emerald-600 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-500 disabled:opacity-60"
                >
                  {{ submitting ? 'Saving…' : mode === 'create' ? 'Create' : 'Save changes' }}
                </button>
              </div>
            </form>
          </DialogPanel>
        </TransitionChild>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

// react-zustand/src/components/ProductForm.tsx
import {
	Dialog,
	DialogPanel,
	DialogTitle,
	Transition,
	TransitionChild,
} from '@headlessui/react'
import {
	Fragment,
	type ReactNode,
	type SubmitEvent,
	useEffect,
	useId,
	useState,
} from 'react'
import { useProductsStore } from '../store'
import type { Product, ProductDraft } from '../types/product'

interface Props {
	open: boolean
	onClose: () => void
	mode: 'create' | 'edit'
	product?: Product
}

const empty: ProductDraft = {
	title: '',
	description: '',
	category: 'smartphones',
	price: 0,
	discountPercentage: 0,
	stock: 0,
	brand: '',
}

export default function ProductForm({ open, onClose, mode, product }: Props) {
	const { createProduct, updateProduct } = useProductsStore()
	const [draft, setDraft] = useState<ProductDraft>(empty)
	const [submitting, setSubmitting] = useState(false)
	const [error, setError] = useState<string | null>(null)

	useEffect(() => {
		if (!open) return

		if (mode === 'edit' && product) {
			setDraft({
				title: product.title,
				description: product.description,
				category: product.category,
				price: product.price,
				discountPercentage: product.discountPercentage,
				stock: product.stock,
				brand: product.brand ?? '',
			})
		} else {
			setDraft(empty)
		}
		setError(null)
	}, [open, mode, product])

	function update<K extends keyof ProductDraft>(
		key: K,
		value: ProductDraft[K],
	) {
		setDraft((d) => ({ ...d, [key]: value }))
	}

	async function onSubmit(evt: SubmitEvent<HTMLFormElement>) {
		evt.preventDefault()
		setSubmitting(true)
		setError(null)

		try {
			if (mode === 'create') {
				await createProduct(draft)
			} else if (product) {
				await updateProduct(product.id, draft)
			}
			onClose()
		} catch (err) {
			setError(err instanceof Error ? err.message : 'Save failed')
		} finally {
			setSubmitting(false)
		}
	}

	return (
		<Transition show={open} as={Fragment}>
			<Dialog onClose={onClose} className="relative z-50">
				<TransitionChild
					as={Fragment}
					enter="ease-out duration-200"
					enterFrom="opacity-0"
					enterTo="opacity-100"
					leave="ease-in duration-150"
					leaveFrom="opacity-100"
					leaveTo="opacity-0"
				>
					<div className="fixed inset-0 bg-slate-900/40" aria-hidden="true" />
				</TransitionChild>
				<div className="fixed inset-0 flex items-center justify-center p-4">
					<TransitionChild
						as={Fragment}
						enter="ease-out duration-200"
						enterFrom="opacity-0 scale-95"
						enterTo="opacity-100 scale-100"
						leave="ease-in duration-150"
						leaveFrom="opacity-100 scale-100"
						leaveTo="opacity-0 scale-95"
					>
						<DialogPanel className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl">
							<DialogTitle className="text-lg font-semibold">
								{mode === 'create'
									? 'New product'
									: `Edit: ${product?.title ?? ''}`}
							</DialogTitle>
							<form onSubmit={onSubmit} className="mt-4 space-y-4">
								<Field label="Title">
									<input
										required
										value={draft.title}
										onChange={(evt) => update('title', evt.target.value)}
										className={inputCls}
									/>
								</Field>
								<Field label="Description">
									<textarea
										rows={3}
										value={draft.description}
										onChange={(evt) => update('description', evt.target.value)}
										className={inputCls}
									/>
								</Field>
								<div className="grid grid-cols-2 gap-3">
									<Field label="Category">
										<input
											value={draft.category}
											onChange={(evt) => update('category', evt.target.value)}
											className={inputCls}
										/>
									</Field>
									<Field label="Brand">
										<input
											value={draft.brand ?? ''}
											onChange={(evt) => update('brand', evt.target.value)}
											className={inputCls}
										/>
									</Field>
								</div>
								<div className="grid grid-cols-3 gap-3">
									<Field label="Price">
										<input
											type="number"
											step="0.01"
											min="0"
											value={draft.price}
											onChange={(evt) =>
												update('price', Number(evt.target.value))
											}
											className={inputCls}
										/>
									</Field>
									<Field label="Discount %">
										<input
											type="number"
											step="0.01"
											min="0"
											value={draft.discountPercentage}
											onChange={(evt) =>
												update('discountPercentage', Number(evt.target.value))
											}
											className={inputCls}
										/>
									</Field>
									<Field label="Stock">
										<input
											type="number"
											min="0"
											value={draft.stock}
											onChange={(evt) =>
												update('stock', Number(evt.target.value))
											}
											className={inputCls}
										/>
									</Field>
								</div>
								{error && <p className="text-sm text-rose-600">{error}</p>}
								<div className="flex justify-end gap-2 pt-2">
									<button
										type="button"
										onClick={onClose}
										className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
									>
										Cancel
									</button>
									<button
										type="submit"
										disabled={submitting}
										className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-500 disabled:opacity-60"
									>
										{submitting
											? 'Saving…'
											: mode === 'create'
												? 'Create'
												: 'Save changes'}
									</button>
								</div>
							</form>
						</DialogPanel>
					</TransitionChild>
				</div>
			</Dialog>
		</Transition>
	)
}

const inputCls =
	'mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500'

function Field({ label, children }: { label: string; children: ReactNode }) {
	const id = useId()

	return (
		<label htmlFor={id} className="block">
			<span className="text-sm font-medium text-slate-700">{label}</span>
			{children}
		</label>
	)
}
